---
- hosts: webserver
  tasks:
    - name: Install packages
      apt: name={{ item }} state=absent
      with_items: 
        - vim
        - git 
        - curl
        - unzip
        - nginx
        - nginx-common
        - nginx-core