---
- hosts: webserver
  tasks:
    - name : Install the nginx webserver
      apt: pkg=nginx state=installed update_cache=true
      notify :
        - start nginx

    - name : Upload default index.html for host
      copy : src = static_files/index.nginx-debian.html dest=/var/www/html/ mode=0644
  handlers:
    - name: start nginx
      service: name=nginx state=started

